name: Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-14
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.app/Contents/Developer"
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -only-testing:WebUITests \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.0" \
            -resultBundlePath TestResults/unit_test_result_bundle

      - name: Run UI Tests
        run: |
          xcodebuild test-without-building \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -only-testing:ExamplesUITests \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.0" \
            -resultBundlePath TestResults/ui_test_result_bundle
