name: Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    name: Unit Test
    runs-on: macos-14
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.app/Contents/Developer"
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run Tests
        run: |
          xcodebuild test \
            -project Examples/Examples.xcodeproj \
            -scheme Examples \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.0" \
            -resultBundlePath TestResults/result_bundle
